name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports: [ "5432:5432" ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Install Postgres client
        run: sudo apt-get -y install libpq-dev

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install frontend dependencies and build assets
        run: |
          yarn install
          bundle exec rails webpacker:compile

      - name: Run tests
        env:
          RUBYOPT: "-W:no-deprecated"
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake test
